spring.application.name=AzureCloud
storage.queue.endpoint=https://storageaccsauravaz.queue.core.windows.net/
mi.clientId = 2f571c59-ca45-42dc-859c-27139978b654
event.hub.ns= event-hub-ns-sauravaz.servicebus.windows.net